import Image from 'next/image'
import './globals.css'

import Footer from '@sambhav/components/Footer'




export const metadata = {
  title: 'Google clone',
  description: 'Generated by perceptron10100',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen" >
       
      <div class="h-14 bg-gradient-to-r from-purple-500 to-pink-500">

        {children}
        </div>
        <Footer/>
        </body>
    </html>
  )
}
